## Вычисления с помощью NumPy
### Задание 1

In [4]:
import numpy as np

In [18]:
b = np.array([1, 2, 3, 3, 1, 6, 8, 11, 10, 7])
b.resize(2, 5)
a = b.T
print(a)

[[ 1  6]
 [ 2  8]
 [ 3 11]
 [ 3 10]
 [ 1  7]]


In [19]:
mean_a = a.mean(axis=0)
print('Среднее значение по признаку: {}'.format(mean_a))

Среднее значение по признаку: [2.  8.4]


### Задание 2

In [20]:
a_centered = a - mean_a
print(a_centered)

[[-1.  -2.4]
 [ 0.  -0.4]
 [ 1.   2.6]
 [ 1.   1.6]
 [-1.  -1.4]]


### Задание 3

In [25]:
a_centered_sp = np.multiply(a_centered[:, 0], a_centered[:, 1])
print(a_centered_sp)

[ 2.4 -0.   2.6  1.6  1.4]


In [44]:
row_a = a.shape[0]
print('Количество наблюдений (строк) матрицы а: {}'.format(row_a))

Количество наблюдений (строк) матрицы а: 5


In [42]:
div_N1 = a_centered_sp / (row_a - 1)
print('Результат деления матрицы a_centered_sp на (N-1) = {}: \n{}'.format(row_a - 1, div_N1))

Результат деления матрицы a_centered_sp на (N-1) = 4: 
[ 0.6  -0.    0.65  0.4   0.35]


## Работа с данными в Pandas

### Задание 1

In [43]:
import pandas as pd

In [46]:
authors = pd.DataFrame([[1, 'Тургенев'],
                        [2, 'Чехов'],
                        [3,  'Островский']],
             columns = ['author_id', ' author_name'])
authors

author_id  author_name
0          1     Тургенев
1          2        Чехов
2          3   Островский

In [47]:
book = pd.DataFrame([[1, 'Отцы и дети', 450],
                     [1, 'Рудин', 300],
                     [1, 'Дворянское гнездо', 350],
                     [2, 'Толстый и тонкий', 500],
                     [2, 'Дама с собачкой', 450],
                     [3, 'Гроза', 370],
                     [3, 'Таланты и поклонники', 290]],
          columns = ['author_id', ' book_title', 'price'])
book

author_id            book_title  price
0          1           Отцы и дети    450
1          1                 Рудин    300
2          1     Дворянское гнездо    350
3          2      Толстый и тонкий    500
4          2       Дама с собачкой    450
5          3                 Гроза    370
6          3  Таланты и поклонники    290

### Задание 2

In [50]:
authors_price = pd.merge(authors, book, on='author_id', how='inner')
authors_price

author_id  author_name            book_title  price
0          1     Тургенев           Отцы и дети    450
1          1     Тургенев                 Рудин    300
2          1     Тургенев     Дворянское гнездо    350
3          2        Чехов      Толстый и тонкий    500
4          2        Чехов       Дама с собачкой    450
5          3   Островский                 Гроза    370
6          3   Островский  Таланты и поклонники    290

### Задание 3

In [108]:
ind = authors_price['price'].argsort().tail()
top5 = authors_price.loc[list(ind.values)]
top5

author_id  author_name         book_title  price
2          1     Тургенев  Дворянское гнездо    350
5          3   Островский              Гроза    370
0          1     Тургенев        Отцы и дети    450
4          2        Чехов    Дама с собачкой    450
3          2        Чехов   Толстый и тонкий    500

### Задание 4

In [240]:
authors_stat = authors.copy()
authors_stat

author_id  author_name
0          1     Тургенев
1          2        Чехов
2          3   Островский

In [241]:
temporary = authors_price.groupby("author_id").agg({"price": "min"})
temporary.columns = ['min']

authors_stat = pd.merge(authors_stat, temporary, on='author_id', how='inner')
authors_stat

author_id  author_name  min
0          1     Тургенев  300
1          2        Чехов  450
2          3   Островский  290

In [242]:
temporary = authors_price.groupby("author_id").agg({"price": "max"})
temporary.columns = ['max']

authors_stat = pd.merge(authors_stat, temporary, on='author_id', how='inner')
authors_stat

author_id  author_name  min  max
0          1     Тургенев  300  450
1          2        Чехов  450  500
2          3   Островский  290  370

In [243]:
temporary = authors_price.groupby("author_id").agg({"price": "mean"})
temporary.columns = ['average']

authors_stat = pd.merge(authors_stat, temporary, on='author_id', how='inner')
authors_stat

author_id  author_name  min  max     average
0          1     Тургенев  300  450  366.666667
1          2        Чехов  450  500  475.000000
2          3   Островский  290  370  330.000000